GRID_SIZE = 25
CELL_SIZE = 25
DAY_BG_COLOR = (100, 149, 237)
NIGHT_BG_COLOR = (25, 25, 112)
UI_FONT_COLOR = (255, 255, 255)
UI_HEIGHT = 40
CHART_HEIGHT = 100
WINDOW_SIZE = (GRID_SIZE * CELL_SIZE, GRID_SIZE * CELL_SIZE + UI_HEIGHT + CHART_HEIGHT)
FPS = 30

ORC_COLOR = (255, 0, 0)
DWARF_COLOR = (0, 0, 255)
PREDATOR_HIGHLIGHT = (255, 255, 0)

NUM_ORCS = 10
NUM_DWARVES = 10
DAY_DURATION = 50

PREDATOR_ENERGY_LOSS = 0.2
PREY_ENERGY_LOSS = 0.2
PREDATOR_ENERGY_GAIN = 15
REPRODUCTION_THRESHOLD = 40
INITIAL_PREDATOR_ENERGY = 40
INITIAL_PREY_ENERGY = 40
VISION_RADIUS = 5

REINFORCEMENT_INTERVAL = 50
REINFORCEMENT_ENERGY_BOOST = 10
REINFORCEMENT_NEW_ORCS = 2
REINFORCEMENT_NEW_DWARVES = 3

OBSTACLE_COUNT = 20
OBSTACLE_COLOR = (128, 128, 128)

ANIMATION_STEPS = 10

BACKGROUND_MUSIC = "assets/The Battle of the Pelennor Fields.mp3"

SHOW_HEATMAP = False

# Dwarf reproduction tweaks
DWARF_REPRODUCTION_THRESHOLD = 50
DWARF_REPRODUCTION_COST = 0.75

# Resource node settings
RESOURCE_NODE_COUNT = 5
RESOURCE_NODE_ENERGY = 20
RESOURCE_NODE_RESPAWN_INTERVAL = 100

# New: Weather settings
WEATHER_CHANGE_INTERVAL = 100
WEATHER_STATES = ["clear", "rain", "storm"]
RAIN_ENERGY_LOSS_INCREASE = 0.05
STORM_ENERGY_LOSS_INCREASE = 0.1
STORM_MOVEMENT_SLOWDOWN = 0.5  # factor to slow movement in storm

# New: Pack behavior
PACK_RADIUS = 3
PACK_ENERGY_BONUS_MULTIPLIER = 0.1  # Each neighboring predator adds 10% bonus energy gain
