# config.py

GRID_SIZE = 30
CELL_SIZE = 30
DAY_BG_COLOR = (100, 149, 237)
NIGHT_BG_COLOR = (25, 25, 112)
UI_FONT_COLOR = (255, 255, 255)
UI_HEIGHT = 40
CHART_HEIGHT = 100

WINDOW_WIDTH = GRID_SIZE * CELL_SIZE
WINDOW_HEIGHT = GRID_SIZE * CELL_SIZE + UI_HEIGHT + CHART_HEIGHT
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

FPS = 25
FAST_FPS = 90  # used when fast-forward is toggled

ORC_COLOR = (255, 0, 0)
DWARF_COLOR = (0, 0, 255)
PREDATOR_HIGHLIGHT = (255, 255, 0)

NUM_ORCS = 10
NUM_DWARVES = 10
DAY_DURATION = 50

PREDATOR_ENERGY_LOSS = 0.2
PREY_ENERGY_LOSS = 0.2
PREDATOR_ENERGY_GAIN = 15
REPRODUCTION_THRESHOLD = 40
INITIAL_PREDATOR_ENERGY = 40
INITIAL_PREY_ENERGY = 40

REINFORCEMENT_INTERVAL = 50
REINFORCEMENT_ENERGY_BOOST = 10
REINFORCEMENT_NEW_ORCS = 2
REINFORCEMENT_NEW_DWARVES = 3

OBSTACLE_COUNT = 20
OBSTACLE_COLOR = (128, 128, 128)

ANIMATION_STEPS = 15

BACKGROUND_MUSIC = "assets/The Battle of the Pelennor Fields.mp3"
REPRODUCTION_SOUND = "assets/reproduce.wav"

SHOW_HEATMAP = False

DWARF_REPRODUCTION_THRESHOLD = 50
DWARF_REPRODUCTION_COST = 0.75

RESOURCE_NODE_COUNT = 5
RESOURCE_NODE_ENERGY = 20
RESOURCE_NODE_RESPAWN_INTERVAL = 100

WEATHER_CHANGE_INTERVAL = 100
WEATHER_STATES = ["clear", "rain", "storm"]
RAIN_ENERGY_LOSS_INCREASE = 0.05
STORM_ENERGY_LOSS_INCREASE = 0.1
STORM_MOVEMENT_SLOWDOWN = 0.5

PACK_RADIUS = 3
PACK_ENERGY_BONUS_MULTIPLIER = 0.1

# Fallback/global traits
MIN_SPEED = 0.6
MAX_SPEED = 2.0
MIN_VISION_RADIUS = 3
MAX_VISION_RADIUS = 8

KILL_PARTICLE_COUNT = 15
KILL_PARTICLE_LIFETIME = 0.5

MINIMAP_SCALE = 0.2
MINIMAP_PADDING = 10

HIGH_SCORE_FILE = "highscore.txt"

DAY_TEMP_MULTIPLIER = 1.0
NIGHT_TEMP_MULTIPLIER = 1.2

MAX_AGE = 200
TRAIL_LENGTH = 10

MUTATION_RATE = 0.2
MUTATION_AMOUNT = 0.1

RESOURCE_RESPAWN_TIMER = RESOURCE_NODE_RESPAWN_INTERVAL

LOG_OVERLAY_MAX = 5

HEALTH_BAR_HEIGHT = 5
LOW_ENERGY_RATIO = 0.25

# Species-specific traits
ORC_MIN_SPEED = 1.0
ORC_MAX_SPEED = 2.0
DWARF_MIN_SPEED = 0.6
DWARF_MAX_SPEED = 1.5

ORC_MIN_VISION_RADIUS = 5
ORC_MAX_VISION_RADIUS = 8
DWARF_MIN_VISION_RADIUS = 3
DWARF_MAX_VISION_RADIUS = 6

# End conditions
MAX_TURNS = 5000
